import { FunctionDef } from '../../ai-service/common-types.js';

/**
 * Function definition for the internal `compoundActionList` function.
 * This is used by the `handleCompoundAction` handler to structure the response
 * from an internal inference call that generates a list of actions.
 */
export const compoundActionListDef: FunctionDef = {
  name: 'compoundActionList',
  description:
    'Receives the list of actions generated by an internal inference call within the compoundAction handler. This function structures the output of the inference.',
  parameters: {
    type: 'object',
    properties: {
      actions: {
        type: 'array',
        description:
          'An array of actions (like createFile, updateFile) to be executed as part of a compound operation.',
        items: {
          // Define the schema for CompoundActionItem here based on its definition in step-ask-question-types.ts
          type: 'object',
          properties: {
            actionName: {
              type: 'string',
              description: 'The name of the operation to execute (e.g., createFile, updateFile).',
              // Ideally, we could restrict this to known operation names, but string is safer for now.
            },
            params: {
              type: 'object',
              description: 'The parameters required by the specified actionName.',
              // Using a generic object type as params vary significantly between actions.
              // Additional properties are allowed implicitly.
            },
          },
          required: ['actionName', 'params'],
        },
      },
    },
    required: ['actions'],
  },
};
