import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { Service } from '../main/ui/backend/service.js';

export async function transformCode(code: string, id: string, codegenService: Service, outDir?: string) {
  // Ignore node_modules and files that don't look like they use our generator
  if (id.includes('node_modules') || !code.includes('genaicode:generator')) {
    return null;
  }

  // Check if the file imports dynamicFunction
  const importRegex = /import\s*{[^}]*\bdynamicFunction\b[^}]*}\s*from\s*['"][^'"]+['"]/;
  if (!importRegex.test(code)) {
    return null;
  }

  // Determine output path: use outDir if provided, otherwise fall back to src/
  const outputPath = outDir
    ? path.resolve(outDir, 'genaicode-generated.js')
    : path.resolve(process.cwd(), 'src/genaicode-generated.js');

  // Ensure the output directory and file exist
  if (!fs.existsSync(outputPath)) {
    const dir = path.dirname(outputPath);
    if (!fs.existsSync(dir)) {
      fs.mkdirSync(dir, { recursive: true });
    }
    fs.writeFileSync(outputPath, '// AUTO-GENERATED BY GENAICODE VITE PLUGIN - DO NOT EDIT\n\n', 'utf-8');
  }

  let generatedFileContent = fs.readFileSync(outputPath, 'utf-8');
  let transformedCode = code;
  const generatedFunctions: string[] = [];

  // Find all dynamicFunction calls: dynamicFunction("prompt", arg1, arg2...)
  const callRegex = /dynamicFunction\s*\(\s*(['"`])(.*?)\1\s*(?:,\s*(.*?))?\)/g;

  let match;
  while ((match = callRegex.exec(code)) !== null) {
    const fullMatch = match[0];
    const prompt = match[2];
    const argsString = match[3];

    // Calculate number of arguments (roughly)
    let argsLength = 0;
    if (argsString && argsString.trim().length > 0) {
      argsLength = argsString.split(',').length;
    }

    // Generate a unique function name based on the prompt
    const safePrompt = prompt.replace(/[^a-zA-Z0-9]/g, '_').substring(0, 20);
    const hash = crypto.createHash('md5').update(prompt).digest('hex').substring(0, 8);
    const funcName = `gen_${safePrompt}_${hash}`;

    generatedFunctions.push(funcName);

    // Check if the function implementation already exists in the generated file
    if (!generatedFileContent.includes(`export function ${funcName}`)) {
      console.log(`[GenAIcode] Generating dynamic function implementation for: "${prompt}"...`);
      try {
        const generatedCode = await codegenService.generateDynamicFunction(prompt, argsLength, funcName, id);
        const formattedCode = `// Prompt: ${prompt}\n${generatedCode}\n`;

        // Append to the physical file
        fs.appendFileSync(outputPath, formattedCode, 'utf-8');
        generatedFileContent += formattedCode;

        console.log(`[GenAIcode] Appended ${funcName} to ${outputPath}`);
      } catch (error) {
        console.error(`[GenAIcode] Failed to generate function for prompt: "${prompt}"`, error);
      }
    }

    // Replace the dynamicFunction call with the generated function name
    const replacement = argsString ? `${funcName}(${argsString})` : `${funcName}()`;
    transformedCode = transformedCode.replace(fullMatch, replacement);
  }

  if (generatedFunctions.length > 0) {
    // Calculate relative path from the current source file to the generated file
    const fileDir = path.dirname(id);
    let relativePath = path.relative(fileDir, outputPath);

    // Ensure it starts with ./
    if (!relativePath.startsWith('.')) {
      relativePath = './' + relativePath;
    }

    // Normalize to .js extension for ES module imports
    relativePath = relativePath.replace(/\.ts$/, '.js');

    const newImport = `import { ${[...new Set(generatedFunctions)].join(', ')} } from '${relativePath}';`;
    transformedCode = transformedCode.replace(importRegex, newImport);
  }

  return {
    code: transformedCode,
    map: null,
  };
}
